services:
  backend:
    container_name: rustapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@localhost:5432/mspri1-2-address

  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: mspri1-2-address
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"



volumes:
  postgres:
