[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
dotenv = "0.15.0"
entities = { path = "../entities" }
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
migration = { path = "../migration" }
[dependencies.sea-orm]
